///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ng_mss_automation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MSS_AutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8ff77ae7-3c50-4c77-a67e-37f03f3d3338")]
    public partial class MSS_AutomationRepository : RepoGenBaseFolder
    {
        static MSS_AutomationRepository instance = new MSS_AutomationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MSS_AutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("8ff77ae7-3c50-4c77-a67e-37f03f3d3338")]
        public static MSS_AutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MSS_AutomationRepository() 
            : base("MSS_AutomationRepository", "/", null, 0, false, "8ff77ae7-3c50-4c77-a67e-37f03f3d3338", ".\\RepositoryImages\\MSS_AutomationRepository8ff77ae7.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8ff77ae7-3c50-4c77-a67e-37f03f3d3338")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MSS_AutomationRepositoryFolders
    {
    }
#pragma warning restore 0436
}
